### ISSUE TITLE
Storage space question

### ISSUE THREAD

**Issue by lesleyrs** [timothyqiu/gdfxr#5]
Hi, I haven't tried this plugin yet but after watching a video about it am I right by saying that you can use generated sfxr sound effects in your game without having to store it as a wav by just using the parameters?

If so, does that mean that this plugin basically trades smaller game size for performance? Or is it just for convenience and the plugin itself negates the smaller game size?

Regardless, I think a modern standalone of sfxr could be nice. As the only other one being updated (rfxgen) isn't compatible with sfxr and the owner simply closed my issue about it.

**Comment by timothyqiu** [comment]
Hi, gdfxr saves your _repository_ space but not your game size. For an exported game, the performance and space requirement is the same as using an exported wav file.

The general import process of Godot is that the editor will convert a foreign file into a Godot resource, and save that resource into the `.import` folder (or `.godot/imported` folder if you're using Godot 4). It's that file in the `.import` folder that's used by the engine.

For example, if you're using a `example.wav` file, the editor automatically converts it into an `AudioStreamSample` resource and save it as `.import/example.wav.tres`. So when accessing `example.wav`, you're actually accessing `.import/example.wav.tres`. In an exported game, only the imported `.import/example.wav.tres` will be included, not the foreign `example.wav` file.

gdfxr provides an import plugin. When the editor wants to convert `example.sfxr` into a known resource, it helps to generate the `AudioStreamSample`, which is essentially the same as what you get when loading a corresponding wav file.

* It saves repository space because the `.import` folder is recommended to be ignored by VCS like git. (All the files in that folder will be regenerated if you open the project in editor.)
* The performance and space requirement is the same as using a wav file in an exported game, because the game only use the imported `.import/example.sfxr.tres`, but not the `example.sfxr` file.

**Comment by lesleyrs** [comment]
Ah ok, so you never get a `.wav` file it goes straight from `example.sfxr` to `AudioStreamSample`.

Thx a lot!
